#!/bin/sh
# Generates DeviceKey.generated.swift (gitignored) from the local pairing key
# and the Mac's Bonjour name. Run automatically as an Xcode pre-build phase.
set -eu
OUT="$(cd "$(dirname "$0")/.." && pwd)/AgentTap/Config/DeviceKey.generated.swift"
# AGENTTAP_NO_KEY=1 (an xcodebuild setting) forces a keyless, display-only
# build — the shape a public binary ships in before runtime pairing.
if [ "${AGENTTAP_NO_KEY:-0}" = "1" ]; then
  KEY=""
else
  KEY="${VIBEPULSE_DEVICE_KEY:-}"
fi
if [ "${AGENTTAP_NO_KEY:-0}" != "1" ] && [ -z "$KEY" ] && [ -f "$HOME/.vibepulse-device-key" ]; then
  KEY=$(tr -d ' \t\r\n' < "$HOME/.vibepulse-device-key")
fi
case "$KEY" in (*[!0-9a-f]*) KEY="" ;; esac
if [ -n "$KEY" ] && [ "${#KEY}" -ne 64 ]; then KEY=""; fi
[ -n "$KEY" ] || echo "gen-device-key: no valid key found; watch will be display-only" >&2
HOST="localhost"
if command -v scutil >/dev/null 2>&1; then
  LH=$(scutil --get LocalHostName 2>/dev/null || true)
  [ -n "$LH" ] && HOST="$LH.local"
fi
mkdir -p "$(dirname "$OUT")"
cat > "$OUT" <<SWIFT
// Generated by watch/tools/gen-device-key.sh — never commit this file.
enum DeviceKey {
    static let hex = "$KEY"
}

enum GeneratedDefaults {
    static let serverBase = "http://$HOST:8737"
}
SWIFT
echo "gen-device-key: wrote $OUT (key: $([ -n "$KEY" ] && echo present || echo absent), host: $HOST)"
